# Generated by Django 6.0.4 on 2026-05-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Subida el')),
            ],
            options={
                'verbose_name': 'Foto de galería',
                'verbose_name_plural': 'Fotos de galería',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('text', models.TextField(max_length=280, verbose_name='Mensaje')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('attending', models.BooleanField(verbose_name='¿Asistirá?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
            ],
            options={
                'verbose_name': 'Confirmación de asistencia',
                'verbose_name_plural': 'Confirmaciones de asistencia',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Canción / Artista')),
                ('link', models.URLField(blank=True, verbose_name='Link de Spotify')),
                ('requester', models.CharField(max_length=80, verbose_name='La pide')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Pedida el')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-created'],
            },
        ),
    ]
