# Generated by Django 6.0.4 on 2026-05-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='email',
        ),
    ]
